"""
The compatibility layer between SQLite and Postgres.

These tests need no Postgres server — they check the translation and the schema
alone. End-to-end coverage against a real database comes from running the whole
suite with DATABASE_URL_TEST set; see tests/base.py.
"""
from __future__ import annotations

import pathlib
import unittest

from app import db


class PlaceholderTranslation(unittest.TestCase):
    def test_question_marks_become_percent_s(self) -> None:
        self.assertEqual(
            db.to_postgres_sql("SELECT * FROM items WHERE id = ? AND sku = ?"),
            "SELECT * FROM items WHERE id = %s AND sku = %s",
        )

    def test_question_mark_inside_a_string_literal_is_left_alone(self) -> None:
        """A question mark inside a string is content, not a parameter."""
        self.assertEqual(
            db.to_postgres_sql("SELECT * FROM t WHERE note = 'why?' AND id = ?"),
            "SELECT * FROM t WHERE note = 'why?' AND id = %s",
        )

    def test_sql_without_parameters_is_unchanged(self) -> None:
        sql = "SELECT COUNT(*) AS n FROM issuances"
        self.assertEqual(db.to_postgres_sql(sql), sql)

    def test_the_real_status_filter_translates(self) -> None:
        """The pattern built dynamically in list_issuances."""
        self.assertEqual(
            db.to_postgres_sql("SELECT * FROM issuances WHERE status IN (?,?,?) LIMIT ?"),
            "SELECT * FROM issuances WHERE status IN (%s,%s,%s) LIMIT %s",
        )


class NoPercentInSql(unittest.TestCase):
    """
    A guard test. The translation to Postgres relies on `%` never appearing in the
    SQL, because psycopg gives it a meaning of its own. A future query with
    LIKE '%...%' would break in the cloud alone — so it fails here instead,
    early and plainly.
    """

    FILES = ("app/repo.py", "app/inventory.py")

    def test_sql_modules_contain_no_percent_sign(self) -> None:
        root = pathlib.Path(__file__).resolve().parent.parent
        offenders = [name for name in self.FILES if "%" in (root / name).read_text(encoding="utf-8")]
        self.assertEqual(
            offenders,
            [],
            "found '%' in the SQL. psycopg reads it as a format marker, so it has to "
            "be doubled to '%%' or to_postgres_sql has to be extended. See app/db.py.",
        )


class SchemaGeneration(unittest.TestCase):
    def test_sqlite_schema_uses_plain_primary_key(self) -> None:
        sql = db.SCHEMA.replace("{pk}", db._PK_SQLITE)
        self.assertIn("id            INTEGER PRIMARY KEY", sql)
        self.assertNotIn("{pk}", sql)

    def test_postgres_schema_uses_identity(self) -> None:
        sql = db.SCHEMA.replace("{pk}", db._PK_POSTGRES)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", sql)
        self.assertNotIn("{pk}", sql)

    def test_identity_is_by_default_so_migration_can_keep_ids(self) -> None:
        """ALWAYS would block inserting an explicit id, and the migration script depends on it."""
        self.assertNotIn("GENERATED ALWAYS", db._PK_POSTGRES)

    def test_every_table_gets_a_primary_key(self) -> None:
        self.assertEqual(db.SCHEMA.count("{pk}"), 5)

    def test_statement_splitting_matches_table_count(self) -> None:
        statements = db._split_statements(db.SCHEMA.replace("{pk}", db._PK_POSTGRES))
        self.assertEqual(len(statements), 5)
        self.assertTrue(all(s.upper().startswith(("CREATE", "--")) for s in statements))


class EngineSelection(unittest.TestCase):
    """The choice is made at runtime, so the engine can be switched between tests."""

    def setUp(self) -> None:
        from app import config

        self._url = config.DATABASE_URL

    def tearDown(self) -> None:
        from app import config

        config.DATABASE_URL = self._url

    def test_empty_url_means_sqlite(self) -> None:
        from app import config

        config.DATABASE_URL = ""
        self.assertFalse(db.is_postgres())

    def test_url_means_postgres(self) -> None:
        from app import config

        config.DATABASE_URL = "postgresql://user:pw@host/db"
        self.assertTrue(db.is_postgres())


if __name__ == "__main__":
    unittest.main()
