"""
שכבת מסד הנתונים — SQLite מקומית, PostgreSQL בענן.

בחירת המנוע היא לפי `DATABASE_URL` בלבד: מוגדר → Postgres, ריק → SQLite.
הסכימה, השאילתות וההתנהגות זהות בשני המצבים, ולכן שאר המערכת לא יודעת
מול מי היא עובדת ואינה צריכה לדעת.

הסכימה קטנה ויציבה, ולכן SQL ישיר קריא יותר מ-ORM כאן. כל התאריכים נשמרים
כמחרוזות ISO-8601 ב-UTC, וההמרה לאזור הזמן המקומי נעשית רק בתצוגה.
"""
from __future__ import annotations

import sqlite3
import threading
from collections.abc import Iterator
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app import config

#: שורה מהמסד. `sqlite3.Row` ו-dict של psycopg תומכים שניהם בגישה לפי שם
#: עמודה (`row["sku"]`), ולכן שאר הקוד לא צריך לדעת מול מי הוא עובד.
Row = Any

# מפתח ראשי מתגדל. זה ההבדל היחיד בין הדיאלקטים בסכימה עצמה, ולכן הוא
# מוזרק כתחליף ואין שתי סכימות שעלולות להיפרד זו מזו.
_PK_SQLITE = "INTEGER PRIMARY KEY"
# BY DEFAULT ולא ALWAYS: מאפשר להכניס מזהה מפורש, וכך סקריפט ההעברה
# משמר את המזהים המקוריים ואיתם את הקשרים בין הטבלאות.
_PK_POSTGRES = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

SCHEMA = """
CREATE TABLE IF NOT EXISTS items (
    id            {pk},
    sku           TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    standard_qty  INTEGER NOT NULL CHECK (standard_qty >= 0),
    active        INTEGER NOT NULL DEFAULT 1,
    notes         TEXT,
    created_at    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS issuances (
    id          {pk},
    -- מפתח הדדופליקציה: מייל שנקלט לא ייספר פעמיים לעולם.
    message_id  TEXT    NOT NULL UNIQUE,
    email_date  TEXT    NOT NULL,
    recipient   TEXT,
    issuer      TEXT,
    center      TEXT,
    raw_text    TEXT    NOT NULL,
    status      TEXT    NOT NULL CHECK (status IN ('applied', 'needs_review', 'ignored')),
    source      TEXT    NOT NULL CHECK (source IN ('email', 'paste')),
    review_note TEXT,
    -- טביעת אצבע של תוכן ההנפקה (מקבל, מנפיק, פריטים וכמויות).
    -- מזהה העברה חוזרת של אותה הנפקה, שמקבלת Message-ID חדש בכל פעם.
    content_key TEXT,
    created_at  TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS issuance_lines (
    id           {pk},
    issuance_id  INTEGER NOT NULL REFERENCES issuances(id) ON DELETE CASCADE,
    raw_sku      TEXT    NOT NULL,
    raw_name     TEXT    NOT NULL,
    qty          INTEGER NOT NULL CHECK (qty > 0),
    item_id      INTEGER REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS adjustments (
    id         {pk},
    item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    -- delta חיובי = מלאי שנוסף (אספקה/החזרה), ולכן מקטין את החוסר.
    delta      INTEGER NOT NULL,
    reason     TEXT    NOT NULL,
    kind       TEXT    NOT NULL CHECK (kind IN ('edit', 'reset')),
    created_at TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS import_runs (
    id             {pk},
    filename       TEXT    NOT NULL,
    created_count  INTEGER NOT NULL DEFAULT 0,
    updated_count  INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    report         TEXT    NOT NULL DEFAULT '',
    created_at     TEXT    NOT NULL
);

"""

# האינדקסים נוצרים *אחרי* המיגרציה, ולא כחלק מ-SCHEMA: על מסד קיים
# הטבלה כבר קיימת ולכן CREATE TABLE מדולג, אבל אינדקס על עמודה חדשה
# היה מפיל את כל הסקריפט לפני שהמיגרציה הוסיפה אותה.
INDEXES = """
CREATE INDEX IF NOT EXISTS ix_lines_issuance ON issuance_lines(issuance_id);
CREATE INDEX IF NOT EXISTS ix_lines_item     ON issuance_lines(item_id);
CREATE INDEX IF NOT EXISTS ix_adj_item       ON adjustments(item_id);
CREATE INDEX IF NOT EXISTS ix_iss_status     ON issuances(status);
CREATE INDEX IF NOT EXISTS ix_iss_content    ON issuances(content_key);
"""

_local = threading.local()


def is_postgres() -> bool:
    """
    נבדק בכל קריאה ולא פעם אחת בטעינה, כי הטסטים מחליפים מנוע בזמן ריצה.
    """
    return bool(config.DATABASE_URL)


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def parse_dt(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return None
    return parsed.replace(tzinfo=timezone.utc) if parsed.tzinfo is None else parsed


# ------------------------------------------------------------------ תרגום SQL


def to_postgres_sql(sql: str) -> str:
    """
    ממיר את סימני הפרמטר של SQLite (`?`) לתחביר של psycopg (`%s`).

    סימן שאלה בתוך מחרוזת SQL אינו פרמטר ולכן אינו מתורגם. אין בפרויקט
    שום `%` בתוך SQL, ולכן אין מה לברוח ממנו — ובדיקה שומרת על זה.
    """
    out: list[str] = []
    in_string = False
    for char in sql:
        if char == "'":
            in_string = not in_string
        if char == "?" and not in_string:
            out.append("%s")
        else:
            out.append(char)
    return "".join(out)


def _split_statements(script: str) -> list[str]:
    """psycopg לא מריץ סקריפט רב-הוראות, ולכן מפרידים לפי `;`."""
    return [part.strip() for part in script.split(";") if part.strip()]


# ------------------------------------------------------------------- חיבורים


class _PostgresConnection:
    """
    מתאם דק שנותן ל-psycopg את אותו ממשק שיש ל-`sqlite3.Connection`.

    קיים כדי ש-repo.py יישאר כתוב בדיאלקט אחד: אותן שאילתות עם `?`
    רצות מול שני המנועים, ואין עותק שני של ה-SQL שעלול להיפרד.
    """

    def __init__(self, raw: Any) -> None:
        self.raw = raw

    def execute(self, sql: str, params: Any = ()) -> Any:
        return self.raw.execute(to_postgres_sql(sql), tuple(params))

    def executemany(self, sql: str, seq_of_params: Any) -> Any:
        cur = self.raw.cursor()
        cur.executemany(to_postgres_sql(sql), [tuple(p) for p in seq_of_params])
        return cur

    def close(self) -> None:
        self.raw.close()


def _connect_sqlite() -> sqlite3.Connection:
    path = config.DB_PATH
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path, timeout=15, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA busy_timeout=15000")
    return conn


def _connect_postgres() -> _PostgresConnection:
    # ייבוא עצל: מי שמריץ מקומית מול SQLite לא חייב את psycopg מותקן.
    import psycopg
    from psycopg.rows import dict_row

    # autocommit משחזר את התנהגות SQLite כאן (isolation_level=None):
    # הוראה בודדת נסגרת מיד, וטרנזקציה נפתחת רק במפורש ב-transaction().
    #
    # prepare_threshold=None מכבה prepared statements. ספקים מנוהלים רבים
    # (בהם Supabase) מציעים חיבור דרך PgBouncer במצב טרנזקציה, ושם prepared
    # statement שנוצר בחיבור אחד נעלם בחיבור הבא ומפיל את השאילתה. בקנה
    # המידה כאן ההאצה שלהם זניחה, והעמידות שווה יותר.
    raw = psycopg.connect(
        config.DATABASE_URL,
        autocommit=True,
        row_factory=dict_row,
        prepare_threshold=None,
    )
    return _PostgresConnection(raw)


def connect() -> Any:
    """
    חיבור לכל thread בנפרד (השרת מרובה-threads ויש גם thread של התזמון).

    ב-SQLite מצב WAL מאפשר קריאות במקביל לכתיבה. ב-Postgres כל חיבור הוא
    משאב אמיתי בשרת, ולכן חשוב לסגור אותו בסוף הבקשה —
    ראו close_thread_connection().
    """
    conn = getattr(_local, "conn", None)
    if conn is not None:
        return conn
    conn = _connect_postgres() if is_postgres() else _connect_sqlite()
    _local.conn = conn
    return conn


@contextmanager
def transaction() -> Iterator[Any]:
    """טרנזקציה אחת. כישלון באמצע מגלגל הכל אחורה."""
    conn = connect()
    # ב-SQLite נועלת מיד ומונעת שדרוג נעילה באמצע; ב-Postgres אין צורך.
    conn.execute("BEGIN" if is_postgres() else "BEGIN IMMEDIATE")
    try:
        yield conn
    except Exception:
        conn.execute("ROLLBACK")
        raise
    conn.execute("COMMIT")


def insert_returning_id(conn: Any, sql: str, params: Any) -> int:
    """
    מזהה השורה שנוצרה. `lastrowid` הוא מושג של SQLite בלבד, ולכן
    ב-Postgres מבקשים אותו מפורשות עם RETURNING.
    """
    if is_postgres():
        row = conn.execute(sql + " RETURNING id", params).fetchone()
        return int(row["id"])
    return int(conn.execute(sql, params).lastrowid)


# --------------------------------------------------------------- סכימה ואתחול


def _existing_columns(conn: Any, table: str) -> set[str]:
    if is_postgres():
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = ?",
            (table,),
        )
        return {row["column_name"] for row in rows}
    return {row[1] for row in conn.execute(f"PRAGMA table_info({table})")}


def _migrate(conn: Any) -> None:
    """
    שינויי סכימה על מסד קיים. חייב להיות בטוח להרצה חוזרת, כי הוא רץ
    בכל עלייה — והמסד של המשתמשת נוצר לפני שהעמודות האלה היו קיימות.
    """
    if "content_key" not in _existing_columns(conn, "issuances"):
        conn.execute("ALTER TABLE issuances ADD COLUMN content_key TEXT")


def _run_script(conn: Any, script: str) -> None:
    if is_postgres():
        for statement in _split_statements(script):
            conn.execute(statement)
    else:
        conn.executescript(script)


def init_db() -> None:
    """סדר קריטי: טבלאות → מיגרציה → אינדקסים."""
    conn = connect()
    pk = _PK_POSTGRES if is_postgres() else _PK_SQLITE
    _run_script(conn, SCHEMA.replace("{pk}", pk))
    _migrate(conn)
    _run_script(conn, INDEXES)


def close_thread_connection() -> None:
    """
    סוגר את החיבור של ה-thread הנוכחי.

    ב-Postgres זה חובה בסוף כל בקשה: לכל thread חיבור משלו, והשרת
    מרובה-threads — בלי סגירה מסודרת נגמרות מכסות החיבורים של הספק.
    """
    conn = getattr(_local, "conn", None)
    if conn is not None:
        try:
            conn.close()
        except Exception:  # חיבור שכבר נסגר או נפל אינו סיבה להפיל בקשה
            pass
        _local.conn = None


def reset_for_tests() -> None:
    """סוגר את החיבור של ה-thread הנוכחי — לשימוש הטסטים בלבד."""
    close_thread_connection()
