"""
The database layer — SQLite locally, PostgreSQL in the cloud.

The engine is chosen by `DATABASE_URL` alone: set → Postgres, empty → SQLite.
The schema, the queries and the behaviour are identical in both modes, so the
rest of the system does not know which one it is talking to, and does not need
to know.

The schema is small and stable, so plain SQL reads better than an ORM here. All
dates are stored as ISO-8601 strings in UTC, and the conversion to the local
timezone happens only for display.
"""
from __future__ import annotations

import sqlite3
import threading
from collections.abc import Iterator
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app import config

#: A row from the database. Both `sqlite3.Row` and psycopg's dict support access
#: by column name (`row["sku"]`), so the rest of the code need not know which of
#: the two it is holding.
Row = Any

# Auto-incrementing primary key. This is the only difference between the two
# dialects in the schema itself, so it is injected as a substitution rather than
# kept as two schemas that could drift apart.
_PK_SQLITE = "INTEGER PRIMARY KEY"
# BY DEFAULT rather than ALWAYS: it allows an explicit id to be inserted, which
# is how the migration script preserves the original ids and, with them, the
# relations between the tables.
_PK_POSTGRES = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

SCHEMA = """
CREATE TABLE IF NOT EXISTS items (
    id            {pk},
    sku           TEXT    NOT NULL UNIQUE,
    name          TEXT    NOT NULL,
    standard_qty  INTEGER NOT NULL CHECK (standard_qty >= 0),
    active        INTEGER NOT NULL DEFAULT 1,
    notes         TEXT,
    created_at    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS issuances (
    id          {pk},
    -- The deduplication key: an email taken in is never counted twice.
    message_id  TEXT    NOT NULL UNIQUE,
    email_date  TEXT    NOT NULL,
    recipient   TEXT,
    issuer      TEXT,
    center      TEXT,
    raw_text    TEXT    NOT NULL,
    status      TEXT    NOT NULL CHECK (status IN ('applied', 'needs_review', 'ignored')),
    source      TEXT    NOT NULL CHECK (source IN ('email', 'paste')),
    review_note TEXT,
    -- Fingerprint of the issuance content (recipient, issuer, items, quantities).
    -- Identifies a re-forward of the same issuance, which gets a fresh
    -- Message-ID every time.
    content_key TEXT,
    created_at  TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS issuance_lines (
    id           {pk},
    issuance_id  INTEGER NOT NULL REFERENCES issuances(id) ON DELETE CASCADE,
    raw_sku      TEXT    NOT NULL,
    raw_name     TEXT    NOT NULL,
    qty          INTEGER NOT NULL CHECK (qty > 0),
    item_id      INTEGER REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS adjustments (
    id         {pk},
    item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    -- A positive delta = stock added (delivery/return), and so reduces the shortage.
    delta      INTEGER NOT NULL,
    reason     TEXT    NOT NULL,
    kind       TEXT    NOT NULL CHECK (kind IN ('edit', 'reset')),
    created_at TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS import_runs (
    id             {pk},
    filename       TEXT    NOT NULL,
    created_count  INTEGER NOT NULL DEFAULT 0,
    updated_count  INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    report         TEXT    NOT NULL DEFAULT '',
    created_at     TEXT    NOT NULL
);

"""

# The indexes are created *after* the migration, and not as part of SCHEMA: on an
# existing database the table already exists so CREATE TABLE is skipped, but an
# index on a new column would bring the whole script down before the migration
# had added it.
INDEXES = """
CREATE INDEX IF NOT EXISTS ix_lines_issuance ON issuance_lines(issuance_id);
CREATE INDEX IF NOT EXISTS ix_lines_item     ON issuance_lines(item_id);
CREATE INDEX IF NOT EXISTS ix_adj_item       ON adjustments(item_id);
CREATE INDEX IF NOT EXISTS ix_iss_status     ON issuances(status);
CREATE INDEX IF NOT EXISTS ix_iss_content    ON issuances(content_key);
"""

_local = threading.local()


def is_postgres() -> bool:
    """
    Checked on every call rather than once at import, because the tests switch
    engines at runtime.
    """
    return bool(config.DATABASE_URL)


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def parse_dt(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return None
    return parsed.replace(tzinfo=timezone.utc) if parsed.tzinfo is None else parsed


# -------------------------------------------------------------- SQL translation


def to_postgres_sql(sql: str) -> str:
    """
    Converts SQLite's parameter markers (`?`) to psycopg's syntax (`%s`).

    A question mark inside an SQL string is not a parameter and so is not
    translated. There is no `%` anywhere in the project's SQL, so there is
    nothing to escape — and a test keeps it that way.
    """
    out: list[str] = []
    in_string = False
    for char in sql:
        if char == "'":
            in_string = not in_string
        if char == "?" and not in_string:
            out.append("%s")
        else:
            out.append(char)
    return "".join(out)


def _split_statements(script: str) -> list[str]:
    """psycopg does not run a multi-statement script, so it is split on `;`."""
    return [part.strip() for part in script.split(";") if part.strip()]


def describe_backend() -> str:
    """
    Which database is actually in use, for the startup log. Never includes the
    password.

    Worth logging because the fallback is silent: a deployment that is missing
    DATABASE_URL quietly starts on an empty SQLite file inside the container,
    serves an empty warehouse, and looks like data loss rather than like a
    configuration mistake.
    """
    if not is_postgres():
        return f"SQLite file at {config.DB_PATH}"
    host = config.DATABASE_URL.split("@")[-1].split("/")[0]
    return f"PostgreSQL at {host}"


# ------------------------------------------------------------------ Connections


class _PostgresConnection:
    """
    A thin adapter giving psycopg the same interface as `sqlite3.Connection`.

    It exists so that repo.py stays written in a single dialect: the same
    queries, with `?`, run against both engines, and there is no second copy of
    the SQL that could drift.
    """

    def __init__(self, raw: Any) -> None:
        self.raw = raw

    def execute(self, sql: str, params: Any = ()) -> Any:
        return self.raw.execute(to_postgres_sql(sql), tuple(params))

    def executemany(self, sql: str, seq_of_params: Any) -> Any:
        cur = self.raw.cursor()
        cur.executemany(to_postgres_sql(sql), [tuple(p) for p in seq_of_params])
        return cur

    def close(self) -> None:
        self.raw.close()


def _connect_sqlite() -> sqlite3.Connection:
    path = config.DB_PATH
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path, timeout=15, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA busy_timeout=15000")
    return conn


def _connect_postgres() -> _PostgresConnection:
    # Lazy import: anyone running locally against SQLite need not have psycopg installed.
    import psycopg
    from psycopg.rows import dict_row

    # autocommit reproduces the SQLite behaviour here (isolation_level=None): a
    # single statement is committed immediately, and a transaction is opened only
    # explicitly, in transaction().
    #
    # prepare_threshold=None disables prepared statements. Many managed providers
    # (Supabase among them) offer a connection through PgBouncer in transaction
    # mode, where a prepared statement created on one connection is gone on the
    # next and takes the query down with it. At this scale the speedup is
    # negligible, and the robustness is worth more.
    raw = psycopg.connect(
        config.DATABASE_URL,
        autocommit=True,
        row_factory=dict_row,
        prepare_threshold=None,
    )
    return _PostgresConnection(raw)


def connect() -> Any:
    """
    A separate connection per thread (the server is multi-threaded and there is
    also the scheduler thread).

    On SQLite, WAL mode allows reads in parallel with a write. On Postgres every
    connection is a real resource on the server, so it matters that it is closed
    at the end of the request — see close_thread_connection().
    """
    conn = getattr(_local, "conn", None)
    if conn is not None:
        return conn
    conn = _connect_postgres() if is_postgres() else _connect_sqlite()
    _local.conn = conn
    return conn


@contextmanager
def transaction() -> Iterator[Any]:
    """A single transaction. A failure midway rolls everything back."""
    conn = connect()
    # On SQLite this locks immediately and avoids a lock upgrade midway; on
    # Postgres there is no need for it.
    conn.execute("BEGIN" if is_postgres() else "BEGIN IMMEDIATE")
    try:
        yield conn
    except Exception:
        conn.execute("ROLLBACK")
        raise
    conn.execute("COMMIT")


def insert_returning_id(conn: Any, sql: str, params: Any) -> int:
    """
    The id of the row just created. `lastrowid` is a SQLite-only notion, so on
    Postgres it is requested explicitly with RETURNING.
    """
    if is_postgres():
        row = conn.execute(sql + " RETURNING id", params).fetchone()
        return int(row["id"])
    return int(conn.execute(sql, params).lastrowid)


# ---------------------------------------------------------- Schema and start-up


def _existing_columns(conn: Any, table: str) -> set[str]:
    if is_postgres():
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = ?",
            (table,),
        )
        return {row["column_name"] for row in rows}
    return {row[1] for row in conn.execute(f"PRAGMA table_info({table})")}


def _migrate(conn: Any) -> None:
    """
    Schema changes on an existing database. Must be safe to run repeatedly,
    because it runs on every start-up — and the user's database was created
    before these columns existed.
    """
    if "content_key" not in _existing_columns(conn, "issuances"):
        conn.execute("ALTER TABLE issuances ADD COLUMN content_key TEXT")


def _run_script(conn: Any, script: str) -> None:
    if is_postgres():
        for statement in _split_statements(script):
            conn.execute(statement)
    else:
        conn.executescript(script)


def init_db() -> None:
    """The order is critical: tables → migration → indexes."""
    conn = connect()
    pk = _PK_POSTGRES if is_postgres() else _PK_SQLITE
    _run_script(conn, SCHEMA.replace("{pk}", pk))
    _migrate(conn)
    _run_script(conn, INDEXES)


def close_thread_connection() -> None:
    """
    Closes the current thread's connection.

    On Postgres this is mandatory at the end of every request: each thread has
    its own connection and the server is multi-threaded — without an orderly
    close, the provider's connection quota runs out.
    """
    conn = getattr(_local, "conn", None)
    if conn is not None:
        try:
            conn.close()
        except Exception:  # an already-closed or broken connection is no reason to fail a request
            pass
        _local.conn = None


def reset_for_tests() -> None:
    """Closes the current thread's connection — for the tests' use only."""
    close_thread_connection()
